# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NingZeta
email: lokhendro At gmail.com
description: >
  Github repositories and blogs from Ningthoujam Lokhendro.
baseurl: ""
url: "http://ningthoujam-lokhendro.github.io" # the base hostname & protocol for your site
twitter_username: ning_lok
github_username:  ningthoujam-lokhendro
author:	Ningthoujam Lokhendro

# Build settings
markdown: kramdown

repository: "ningthoujam-lokhendro/ningthoujam-lokhendro.github.io"
host: ningzeta.com
