version: '3'

services:
  jekyll:
    container_name: jekyll
    image: jekyll/jekyll
    ports:
      - "4000:4000"
    volumes:
            - ".:/srv/jekyll"
    command: jekyll serve --incremental --force_polling
